### ISSUE TITLE
User should be able to create and-style filters

### ISSUE THREAD

**Issue by mcoffin** [mcoffin/harbaror#4]
The config file should be able to accept `and`-style filters like the following.

```yaml
filter:
  - and:
      - query: a
        pattern: foo
      - query: b
        pattern: bar
```
