### ISSUE TITLE
User should be able to create or-style filters

### ISSUE THREAD

**Issue by mcoffin** [mcoffin/harbaror#5]
Config file should accept `or`-style filters like below.

```yaml
or:
  - query: a
    pattern: foo
  - query: b
    pattern: bar
```
